name: BlobStones
version: ${project.version}
main: io.github.anjoismysign.blobstones.BlobStones
api-version: 1.17
load: STARTUP
depend: [ BlobLib, ProtectionStones ]
commands:
  blobstones:
    description: "Opens your ProtectionStones GUI helper"
    usage: "/blobstones"
    aliases: [ bstones, stones ]