name: BlobStones
version: ${project.version}
main: us.mytheria.blobstones.BlobStones
api-version: 1.17
load: STARTUP
commands:
  blobstones:
    description: "Opens your ProtectionStones GUI helper"
    usage: "/blobstones"
    aliases: [ bstones, stones ]