name: Maven Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Maven build
        run: mvn --file ci-pom.xml package

  deploy:

    runs-on: ubuntu-latest

    if: ${{ endsWith(github.event.head_commit.message, '-release') }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Upload shaded jar
        uses: actions/upload-artifact@v3
        with:
          name: shaded-jar
          path: target/*.jar

      - name: Create release
        uses: github-actions/create-release@v5
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: `
            ### Changes since last release

            ${{ steps.get-commits.outputs.stdout }}
          `
