name: Maven Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Maven build
        run: mvn --file ci-pom.xml package

  deploy:

    runs-on: ubuntu-latest

    if: ${{ endsWith(github.event.head_commit.message, '-release') }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Upload shaded jar
        uses: actions/upload-artifact@v3
        with:
          name: shaded-jar
          path: target/*.jar

      - name: Get SHA of last release
        id: get-last-release-sha
        run: |
          echo "::set-output name=sha::$(git describe --tags | tail -n 1)"

      - name: Get list of commits since last release
        id: get-commits
        run: git log ${{ steps.get-last-release-sha.outputs.sha }}..HEAD --no-merges --oneline

      - name: Generate list of commit messages in Markdown format
        id: generate-markdown
        run: |
          echo "### Changes since last release" > commit-list.md
          for commit in $(cat ${{ steps.get-commits.outputs.stdout }}); do
            echo "* $commit" >> commit-list.md
          done

      - name: Add list of commit messages to GitHub release body
        uses: actions/update-release-body@v1
        with:
          body: ${{ steps.generate-markdown.outputs.stdout }}
