name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # [!] we need to checkout with tags and commit history

      - name: 📋 Get Commits since last Release
        id: changes
        uses: simbo/changes-since-last-release-action@v1

      - name: 📣 Output collected Data
        run: |
          echo "Changes since ${{ steps.changes.outputs.last-tag }}:"
          echo "${{ steps.changes.outputs.log }}"
      - name: Update Release Body
        id: update_release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changes.outputs.log }}
